version: "2"
services:
    datapower:
        volumes:
            - '/Users/divya.soniibm.com/.lbmesh.io/datapower/config:/drouter/config'
            - '/Users/divya.soniibm.com/.lbmesh.io/datapower/data:/drouter/local'
        mem_reservation: 1024m
        mem_limit: 4096m
        environment:
            - DATAPOWER_ACCEPT_LICENSE=true
            - DATAPOWER_INTERACTIVE=true
            - DATAPOWER_WORKER_THREADS=2
        ports:
            - '9090:9090'
            - '9022:22'
            - '5550:5550'
            - '9229:9229'
            - '5554:5554'
            - '8000-8010:8000-8010'
        image: ibmcom/datapower:latest
        container_name: lbmesh-integ-datapower    
        networks:
          - lbmesh-integ-datapower
        command: /bin/drouter

networks:
  lbmesh-integ-datapower:                        